{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7fd89806",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from random import sample"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f348437e",
   "metadata": {},
   "source": [
    "# Reading Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8feeac73",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Canara</td>\n",
       "      <td>Canara Robeco Equity tax Saver Direct Growth</td>\n",
       "      <td>Financial/Technology/Consumer/Energy/Healthcar...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>11.37</td>\n",
       "      <td>20.33</td>\n",
       "      <td>16.12</td>\n",
       "      <td>0.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Canara</td>\n",
       "      <td>Canara Robeco Consumer Trends Fund Direct Growth</td>\n",
       "      <td>Financial/Consumer/Automobile/Services/Consume...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>4.0</td>\n",
       "      <td>19.00</td>\n",
       "      <td>19.08</td>\n",
       "      <td>15.92</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Canara</td>\n",
       "      <td>Canara Robeco Conservative Hybrid Fund Direct</td>\n",
       "      <td>Financial/Consumer/Energy/Automobile/Technolog...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Moderately High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>6.13</td>\n",
       "      <td>9.24</td>\n",
       "      <td>9.49</td>\n",
       "      <td>0.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Canara</td>\n",
       "      <td>Canara Robeco Equity Hybrid Fund Direct Growth</td>\n",
       "      <td>Financial/Technology/Energy/Healthcare/Automob...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>4.0</td>\n",
       "      <td>9.62</td>\n",
       "      <td>15.23</td>\n",
       "      <td>12.75</td>\n",
       "      <td>0.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Canara</td>\n",
       "      <td>Canara Robeco Corporate Bond Fund Direct Growth</td>\n",
       "      <td>Financial/Energy/Sovereign/Others</td>\n",
       "      <td>Debt</td>\n",
       "      <td>Low Moderate risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>3.88</td>\n",
       "      <td>5.25</td>\n",
       "      <td>6.72</td>\n",
       "      <td>0.30</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>158</th>\n",
       "      <td>L&amp;T</td>\n",
       "      <td>L&amp;T Flexi bond fund diret growth</td>\n",
       "      <td>Rec Limited /Reliance Industries/Indian Oil Co...</td>\n",
       "      <td>Debt</td>\n",
       "      <td>moderate risk</td>\n",
       "      <td>2.0</td>\n",
       "      <td>11.21</td>\n",
       "      <td>9.61</td>\n",
       "      <td>9.62</td>\n",
       "      <td>1.36</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>159</th>\n",
       "      <td>L&amp;T</td>\n",
       "      <td>L&amp;T Equity Savings Fund Direct Growth</td>\n",
       "      <td>Government Securities/Cash &amp; Cash Equivalents ...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>moderate risk</td>\n",
       "      <td>4.0</td>\n",
       "      <td>4.10</td>\n",
       "      <td>12.30</td>\n",
       "      <td>7.50</td>\n",
       "      <td>0.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>160</th>\n",
       "      <td>L&amp;T</td>\n",
       "      <td>L&amp;T Balanced Advantage Fund - Growth - Direct ...</td>\n",
       "      <td>Financial/Others/Technology/Automobile/Healthc...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>moderate risk</td>\n",
       "      <td>4.0</td>\n",
       "      <td>5.50</td>\n",
       "      <td>10.70</td>\n",
       "      <td>8.20</td>\n",
       "      <td>0.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>161</th>\n",
       "      <td>L&amp;T</td>\n",
       "      <td>L&amp;T Emerging Businesses Fund - Growth - Direct...</td>\n",
       "      <td>Financial/Others/Automobile/Healthcare/Constru...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>high risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>11.50</td>\n",
       "      <td>33.80</td>\n",
       "      <td>13.20</td>\n",
       "      <td>0.75</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>162</th>\n",
       "      <td>L&amp;T</td>\n",
       "      <td>\\nL&amp;T Infrastructure Growth Direct Plan</td>\n",
       "      <td>Financial/Others/Automobile/Healthcare/Constru...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>high risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>14.90</td>\n",
       "      <td>24.90</td>\n",
       "      <td>9.50</td>\n",
       "      <td>1.12</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>163 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "    AMC_Name                                          Fund_Name  \\\n",
       "0     Canara       Canara Robeco Equity tax Saver Direct Growth   \n",
       "1     Canara   Canara Robeco Consumer Trends Fund Direct Growth   \n",
       "2     Canara      Canara Robeco Conservative Hybrid Fund Direct   \n",
       "3     Canara     Canara Robeco Equity Hybrid Fund Direct Growth   \n",
       "4     Canara    Canara Robeco Corporate Bond Fund Direct Growth   \n",
       "..       ...                                                ...   \n",
       "158      L&T                   L&T Flexi bond fund diret growth   \n",
       "159      L&T              L&T Equity Savings Fund Direct Growth   \n",
       "160      L&T  L&T Balanced Advantage Fund - Growth - Direct ...   \n",
       "161      L&T  L&T Emerging Businesses Fund - Growth - Direct...   \n",
       "162      L&T            \\nL&T Infrastructure Growth Direct Plan   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "0    Financial/Technology/Consumer/Energy/Healthcar...   Equity   \n",
       "1    Financial/Consumer/Automobile/Services/Consume...   Equity   \n",
       "2    Financial/Consumer/Energy/Automobile/Technolog...   Hybrid   \n",
       "3    Financial/Technology/Energy/Healthcare/Automob...   Hybrid   \n",
       "4                    Financial/Energy/Sovereign/Others     Debt   \n",
       "..                                                 ...      ...   \n",
       "158  Rec Limited /Reliance Industries/Indian Oil Co...     Debt   \n",
       "159  Government Securities/Cash & Cash Equivalents ...   Hybrid   \n",
       "160  Financial/Others/Technology/Automobile/Healthc...   Hybrid   \n",
       "161  Financial/Others/Automobile/Healthcare/Constru...   Equity   \n",
       "162  Financial/Others/Automobile/Healthcare/Constru...   Equity   \n",
       "\n",
       "                 Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "0          Very High Risk          5.0       11.37       20.33       16.12   \n",
       "1          Very High Risk          4.0       19.00       19.08       15.92   \n",
       "2    Moderately High Risk          5.0        6.13        9.24        9.49   \n",
       "3          Very High Risk          4.0        9.62       15.23       12.75   \n",
       "4       Low Moderate risk          3.0        3.88        5.25        6.72   \n",
       "..                    ...          ...         ...         ...         ...   \n",
       "158         moderate risk          2.0       11.21        9.61        9.62   \n",
       "159         moderate risk          4.0        4.10       12.30        7.50   \n",
       "160         moderate risk          4.0        5.50       10.70        8.20   \n",
       "161             high risk          3.0       11.50       33.80       13.20   \n",
       "162             high risk          3.0       14.90       24.90        9.50   \n",
       "\n",
       "     Expence_Ratio  \n",
       "0             0.61  \n",
       "1             0.99  \n",
       "2             0.56  \n",
       "3             0.62  \n",
       "4             0.30  \n",
       "..             ...  \n",
       "158           1.36  \n",
       "159           0.60  \n",
       "160           0.76  \n",
       "161           0.75  \n",
       "162           1.12  \n",
       "\n",
       "[163 rows x 10 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_excel('./dataset.xlsx')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7f50dfb1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Infrastructure fund direct growth</td>\n",
       "      <td>Capital Goods/Construction/Services/Metals &amp; M...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>10.82</td>\n",
       "      <td>19.48</td>\n",
       "      <td>10.62</td>\n",
       "      <td>1.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Large &amp; mid cap fund direct growth</td>\n",
       "      <td>Financial/Others/Chemicals/Services/Technology...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>1.77</td>\n",
       "      <td>14.62</td>\n",
       "      <td>10.91</td>\n",
       "      <td>0.84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Nifty 50 index fund direct growth</td>\n",
       "      <td>Financial/Otherss/Technology/Energy/Consumer S...</td>\n",
       "      <td>Others</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>7.69</td>\n",
       "      <td>16.58</td>\n",
       "      <td>11.64</td>\n",
       "      <td>0.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF S&amp;P BSE Sensex fund direct growth</td>\n",
       "      <td>Financial/Otherss/Technology/Energy/Consumer S...</td>\n",
       "      <td>Others</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>9.46</td>\n",
       "      <td>16.53</td>\n",
       "      <td>12.61</td>\n",
       "      <td>0.38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Govt. Securities Fund Direct Growth</td>\n",
       "      <td>Sovereign/Financial/Others</td>\n",
       "      <td>Debt</td>\n",
       "      <td>Moderate Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>2.60</td>\n",
       "      <td>4.70</td>\n",
       "      <td>7.80</td>\n",
       "      <td>0.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Liquid Fund Direct Growth</td>\n",
       "      <td>Financial/Services/Others</td>\n",
       "      <td>Debt</td>\n",
       "      <td>Low to Moderate Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>5.40</td>\n",
       "      <td>4.30</td>\n",
       "      <td>5.30</td>\n",
       "      <td>0.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>LIC</td>\n",
       "      <td>LIC MF Debt Hybrid Fund Direct Growth</td>\n",
       "      <td>Financial/Technology/Consumer Staples/Automobi...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Moderately High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>3.20</td>\n",
       "      <td>6.30</td>\n",
       "      <td>6.60</td>\n",
       "      <td>1.34</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   AMC_Name                                   Fund_Name  \\\n",
       "16      LIC    LIC MF Infrastructure fund direct growth   \n",
       "17      LIC   LIC MF Large & mid cap fund direct growth   \n",
       "18      LIC    LIC MF Nifty 50 index fund direct growth   \n",
       "19      LIC    LIC MF S&P BSE Sensex fund direct growth   \n",
       "45      LIC  LIC MF Govt. Securities Fund Direct Growth   \n",
       "46      LIC            LIC MF Liquid Fund Direct Growth   \n",
       "51      LIC       LIC MF Debt Hybrid Fund Direct Growth   \n",
       "\n",
       "                                             Holdings Category  \\\n",
       "16  Capital Goods/Construction/Services/Metals & M...   Equity   \n",
       "17  Financial/Others/Chemicals/Services/Technology...   Equity   \n",
       "18  Financial/Otherss/Technology/Energy/Consumer S...   Others   \n",
       "19  Financial/Otherss/Technology/Energy/Consumer S...   Others   \n",
       "45                         Sovereign/Financial/Others     Debt   \n",
       "46                         Financial/Services/Others      Debt   \n",
       "51  Financial/Technology/Consumer Staples/Automobi...   Hybrid   \n",
       "\n",
       "                Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "16        Very High Risk          3.0       10.82       19.48       10.62   \n",
       "17        Very High Risk          3.0        1.77       14.62       10.91   \n",
       "18        Very High Risk          3.0        7.69       16.58       11.64   \n",
       "19        Very High Risk          3.0        9.46       16.53       12.61   \n",
       "45         Moderate Risk          3.0        2.60        4.70        7.80   \n",
       "46  Low to Moderate Risk          3.0        5.40        4.30        5.30   \n",
       "51  Moderately High Risk          3.0        3.20        6.30        6.60   \n",
       "\n",
       "    Expence_Ratio  \n",
       "16           1.47  \n",
       "17           0.84  \n",
       "18           0.20  \n",
       "19           0.38  \n",
       "45           0.76  \n",
       "46           0.16  \n",
       "51           1.34  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.loc[df.AMC_Name == 'LIC']"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c8c2e7d2",
   "metadata": {},
   "source": [
    "# Displaying Row"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "182204de",
   "metadata": {},
   "outputs": [],
   "source": [
    "def displayrow(df, var):\n",
    "    df1 = df.loc[df['Category'] == var]\n",
    "    \n",
    "    #Extracting Row numbers to a list\n",
    "    a = []\n",
    "    for i in df1.index:\n",
    "        a.append(i)\n",
    "    \n",
    "    #Extracting random 3 rows from dataframe\n",
    "    b = sample(a,3)\n",
    "    \n",
    "    #Creating a new data frame with row present in the list\n",
    "    df11 = df.iloc[b]\n",
    "    \n",
    "    return df11"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cff13c7c",
   "metadata": {},
   "source": [
    "# Displaying Row with Rating Parameter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5d26fa9b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def displayrowwithrating(df, var, star=''):\n",
    "    df1 = df.loc[(df['Category'] == var) & (df['Fund_Rating'] == float(star))]\n",
    "    \n",
    "    #Extracting Row numbers to a list\n",
    "    a = []\n",
    "    for i in df1.index:\n",
    "        a.append(i)\n",
    "    \n",
    "    #Extracting random 3 rows from dataframe\n",
    "    b = sample(a,3)\n",
    "    \n",
    "    #Creating a new data frame with row present in the list\n",
    "    df11 = df.iloc[b]\n",
    "    \n",
    "    return df11"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "70b8123b",
   "metadata": {},
   "source": [
    "# Fetching Row Numbers "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6b665973",
   "metadata": {},
   "source": [
    "tolist() function can be used instead of this..."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "75415412",
   "metadata": {},
   "outputs": [],
   "source": [
    "def convertingtorow(var):\n",
    "    a = []\n",
    "    for i in var:\n",
    "        a.append(i)\n",
    "    return a"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "629b7efb",
   "metadata": {},
   "source": [
    "# Taking Input"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1fbb5fa8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def takeint(var):\n",
    "    while(True):\n",
    "        print('\\nPlease Choose a Fund from above list and Enter the Code Number Written Before AMCName')\n",
    "        choice = input('Please Enter Your Choice: ')\n",
    "        if choice.isnumeric():\n",
    "            choice = int(choice)\n",
    "            if choice in var:\n",
    "                return choice\n",
    "            else:\n",
    "                print('\\nInvalid Input')\n",
    "        else:\n",
    "            print('\\nPlease Enter Correct Number')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "59fb3e94",
   "metadata": {},
   "source": [
    "# Options Function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6e07f181",
   "metadata": {},
   "outputs": [],
   "source": [
    "def options(df, category):\n",
    "    #displaying 3 rows randomly for dataframe using displayrow function\n",
    "    dfequity = displayrow(df, category)\n",
    "    rows = convertingtorow(dfequity.index)\n",
    "    display(dfequity)\n",
    "\n",
    "    #Other Options\n",
    "    while(True):\n",
    "        x = input('Type \"y\" if you want new options \\nType \"a\" if you have a specific AMC in mind.. \\nType \"n\" to continue...')\n",
    "        if x.lower() == 'y':\n",
    "            #displaying 3 rows randomly for dataframe using displayrow function\n",
    "            dfequity = displayrow(df, category)\n",
    "            rows = convertingtorow(dfequity.index)\n",
    "            display(dfequity)\n",
    "            \n",
    "        elif x.lower() == 'a':\n",
    "            print(df.AMC_Name.unique())\n",
    "            y = input(\"Please Enter your Choice: \")\n",
    "            if y in df.AMC_Name.unique():\n",
    "                print(\"Amc of Choice: \",y)\n",
    "                dftemp = df.loc[(df['AMC_Name']==y) & (df['Category']==category)]\n",
    "                rows = convertingtorow(dftemp.index)\n",
    "                display(dftemp)\n",
    "                break\n",
    "            else:\n",
    "                print(\"Invalid AMC\")\n",
    "        elif x.lower() == 'n':\n",
    "            break\n",
    "        else:\n",
    "            print(\"Please Enter Appropriate Response!\")\n",
    "\n",
    "\n",
    "    #getting user's choice\n",
    "    temp = takeint(rows)\n",
    "    print('\\n',df.iloc[temp])\n",
    "    return temp\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9412ff3d",
   "metadata": {},
   "source": [
    "# Options Function with Rating Parameter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e930e885",
   "metadata": {},
   "outputs": [],
   "source": [
    "def optionswithrating(df, category, star=''):\n",
    "    star = float(star)\n",
    "    \n",
    "    #displaying 3 rows randomly for dataframe using displayrow function\n",
    "    dfequity = displayrowwithrating(df, category, star)\n",
    "    rows = convertingtorow(dfequity.index)\n",
    "    display(dfequity)\n",
    "\n",
    "    #Other Options\n",
    "    while(True):\n",
    "        x = input('Type \"y\" if you want new options \\nType \"a\" if you have a specific AMC in mind.. \\nType \"n\" to continue...')\n",
    "        if x.lower() == 'y':\n",
    "            #displaying 3 rows randomly for dataframe using displayrow function\n",
    "            dfequity = displayrowwithrating(df, category, star)\n",
    "            rows = convertingtorow(dfequity.index)\n",
    "            display(dfequity)\n",
    "\n",
    "        elif x.lower() == 'a':\n",
    "            print(df.AMC_Name.unique())\n",
    "            y = input(\"Please Enter your Choice: \")\n",
    "            if y in df.AMC_Name.unique():\n",
    "                print(\"Amc of Choice: \",y)\n",
    "                dftemp = df.loc[(df['AMC_Name']==y) & (df['Category']==category)]\n",
    "                rows = convertingtorow(dftemp.index)\n",
    "                display(dftemp)\n",
    "                break\n",
    "            else:\n",
    "                print(\"Invalid AMC\")\n",
    "        elif x.lower() == 'n':\n",
    "            break\n",
    "        else:\n",
    "            print(\"Please Enter Appropriate Response!\")\n",
    "\n",
    "\n",
    "    #getting user's choice\n",
    "    temp = takeint(rows)\n",
    "    print('\\n',df.iloc[temp])\n",
    "    return temp"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d6b5e7ff",
   "metadata": {},
   "source": [
    "# Calculator Program"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b696f289",
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculator(investment, r, years):\n",
    "    #Returns Calculator\n",
    "\n",
    "    months = years * 12\n",
    "\n",
    "    #Compound Interest Formula\n",
    "    i = r/100/12\n",
    "\n",
    "    #Seperate Calculation for FV\n",
    "    a = (1+i)**months-1\n",
    "    b = (1+i)/i\n",
    "    \n",
    "    #Final Future Value Calculation\n",
    "    FV = investment * a * b\n",
    "    #print(FV)\n",
    "    \n",
    "    return FV"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aff41a74",
   "metadata": {},
   "source": [
    "#  Calculation Function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "67b75f20",
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate(df, amount, age, row):\n",
    "    print(\"\\nFollowing are the Funds you have chosen: \")\n",
    "    display(df.loc[row])\n",
    "    \n",
    "    if amount <= 5000:\n",
    "        if age <= 18:\n",
    "            equity = amount\n",
    "\n",
    "            a = df.loc[row]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(equity, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(equity, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(equity, rate, 5)\n",
    "\n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            equity1 = float(equity1)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=equity1))\n",
    "            \n",
    "            totalgain = equity1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            equity3 = float(equity3)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=equity3))\n",
    "            \n",
    "            totalgain = equity3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            equity5 = float(equity5)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=equity5))\n",
    "            \n",
    "            totalgain = equity5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "\n",
    "        else:\n",
    "            var = 100 - age\n",
    "            per = var/100\n",
    "            equity = amount * per\n",
    "            hybrid = amount - equity\n",
    "            \n",
    "            #For Equity\n",
    "            a = df.loc[row[0]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(equity, rate, 1)\n",
    "            \n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(equity, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(equity, rate, 5)\n",
    "            \n",
    "            #For Hybrid\n",
    "            a = df.loc[row[1]]\n",
    "            rate = a.Return_1Yr\n",
    "            hybrid1 = calculator(hybrid, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            hybrid3 = calculator(hybrid, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            hybrid5 = calculator(hybrid, rate, 5)\n",
    "            \n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year1 = float(equity1) + float(hybrid1)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year1))\n",
    "            \n",
    "            totalgain = Year1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year3 = float(equity3) + float(hybrid3)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year3))\n",
    "            \n",
    "            totalgain = Year3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year5 = float(equity5) + float(hybrid5)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year5))\n",
    "            \n",
    "            totalgain = Year5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "    elif amount > 5000 and amount <= 10000:\n",
    "        if age <= 18:\n",
    "            amount1 = amount/2\n",
    "            amount2 = amount/2\n",
    "\n",
    "            a = df.loc[row[0]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(amount1, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(amount1, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(amount1, rate, 5)\n",
    "            \n",
    "            b = df.loc[row[1]]\n",
    "            rate = b.Return_1Yr\n",
    "            equity21 = calculator(amount2, rate, 1)\n",
    "            \n",
    "            rate = b.Return_3Yr\n",
    "            equity23 = calculator(amount2, rate, 3)\n",
    "\n",
    "            rate = b.Return_5Yr\n",
    "            equity25 = calculator(amount2, rate, 5)\n",
    "\n",
    "\n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year1 = equity1 + equity21\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year1))\n",
    "            \n",
    "            totalgain = Year1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year3 = equity3 + equity23\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year3))\n",
    "            \n",
    "            totalgain = Year3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year5 = equity5 + equity25\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year5))\n",
    "            \n",
    "            totalgain = Year5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "\n",
    "        else:\n",
    "            var = 100 - age\n",
    "            per = var/100\n",
    "            equity = amount * per\n",
    "            var2 = amount - equity\n",
    "            hybrid = var2 / 2\n",
    "            debt = var2 / 2\n",
    "            \n",
    "            #for equity funds\n",
    "            fund1 = equity/2\n",
    "            fund2 = equity/2\n",
    "            \n",
    "            #For Equity Fund 1\n",
    "            a = df.loc[row[0]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(fund1, rate, 1)\n",
    "            \n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(fund1, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(fund1, rate, 5)\n",
    "\n",
    "            #For Equity Fund 2\n",
    "            a = df.loc[row[1]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity21 = calculator(fund2, rate, 1)\n",
    "            \n",
    "            rate = a.Return_3Yr\n",
    "            equity23 = calculator(fund2, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity25 = calculator(fund2, rate, 5)\n",
    "            \n",
    "            \n",
    "            #For Hybrid\n",
    "            a = df.loc[row[2]]\n",
    "            rate = a.Return_1Yr\n",
    "            hybrid1 = calculator(hybrid, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            hybrid3 = calculator(hybrid, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            hybrid5 = calculator(hybrid, rate, 5)\n",
    "\n",
    "            #For Debt\n",
    "            a = df.loc[row[3]]\n",
    "            rate = a.Return_1Yr\n",
    "            debt1 = calculator(debt, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            debt3 = calculator(debt, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            debt5 = calculator(debt, rate, 5)\n",
    "            \n",
    "            \n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year1 = equity1 + equity21 + hybrid1 + debt1\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year1))\n",
    "            \n",
    "            totalgain = Year1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year3 = equity3 + equity23 + hybrid3 + debt3\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year3))\n",
    "            \n",
    "            totalgain = Year3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year5 = equity5 + equity25 + hybrid5 + debt5\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year5))\n",
    "            \n",
    "            totalgain = Year5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "    \n",
    "    elif amount > 10000:\n",
    "        if age <= 18:\n",
    "            amount1 = amount/3\n",
    "            amount2 = amount/3\n",
    "            amount3 = amount/3\n",
    "\n",
    "            a = df.loc[row[0]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(amount1, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(amount1, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(amount1, rate, 5)\n",
    "            \n",
    "            b = df.loc[row[1]]\n",
    "            rate = b.Return_1Yr\n",
    "            equity21 = calculator(amount2, rate, 1)\n",
    "            \n",
    "            rate = b.Return_3Yr\n",
    "            equity23 = calculator(amount2, rate, 3)\n",
    "\n",
    "            rate = b.Return_5Yr\n",
    "            equity25 = calculator(amount2, rate, 5)\n",
    "\n",
    "            c = df.loc[row[2]]\n",
    "            rate = c.Return_1Yr\n",
    "            equity31 = calculator(amount3, rate, 1)\n",
    "            \n",
    "            rate = c.Return_3Yr\n",
    "            equity33 = calculator(amount3, rate, 3)\n",
    "\n",
    "            rate = c.Return_5Yr\n",
    "            equity35 = calculator(amount3, rate, 5)\n",
    "            \n",
    "\n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year1 = equity1 + equity21 + equity31\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year1))\n",
    "            \n",
    "            totalgain = Year1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year3 = equity3 + equity23 + equity33\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year3))\n",
    "            \n",
    "            totalgain = Year3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year5 = equity5 + equity25 + equity35\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year5))\n",
    "            \n",
    "            totalgain = Year5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "\n",
    "        else:\n",
    "            var = 100 - age\n",
    "            per = var/100\n",
    "            equity = amount * per\n",
    "            var2 = amount - equity\n",
    "            hybrid = var2 / 2\n",
    "            debt = var2 / 2\n",
    "            \n",
    "            #for equity funds\n",
    "            fund1 = equity/3\n",
    "            fund2 = equity/3\n",
    "            fund3 = equity/3\n",
    "            \n",
    "            #For Equity Fund 1\n",
    "            a = df.loc[row[0]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity1 = calculator(fund1, rate, 1)\n",
    "            \n",
    "            rate = a.Return_3Yr\n",
    "            equity3 = calculator(fund1, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity5 = calculator(fund1, rate, 5)\n",
    "\n",
    "            #For Equity Fund 2\n",
    "            a = df.loc[row[1]]\n",
    "            rate = a.Return_1Yr\n",
    "            equity21 = calculator(fund2, rate, 1)\n",
    "            \n",
    "            rate = a.Return_3Yr\n",
    "            equity23 = calculator(fund2, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            equity25 = calculator(fund2, rate, 5)\n",
    "\n",
    "            #For Equity Fund 3\n",
    "            c = df.loc[row[2]]\n",
    "            rate = c.Return_1Yr\n",
    "            equity31 = calculator(fund3, rate, 1)\n",
    "            \n",
    "            rate = c.Return_3Yr\n",
    "            equity33 = calculator(fund3, rate, 3)\n",
    "\n",
    "            rate = c.Return_5Yr\n",
    "            equity35 = calculator(fund3, rate, 5)\n",
    "            \n",
    "            \n",
    "            #For Hybrid\n",
    "            a = df.loc[row[3]]\n",
    "            rate = a.Return_1Yr\n",
    "            hybrid1 = calculator(hybrid, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            hybrid3 = calculator(hybrid, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            hybrid5 = calculator(hybrid, rate, 5)\n",
    "\n",
    "            #For Debt\n",
    "            a = df.loc[row[4]]\n",
    "            rate = a.Return_1Yr\n",
    "            debt1 = calculator(debt, rate, 1)\n",
    "\n",
    "            rate = a.Return_3Yr\n",
    "            debt3 = calculator(debt, rate, 3)\n",
    "\n",
    "            rate = a.Return_5Yr\n",
    "            debt5 = calculator(debt, rate, 5)\n",
    "            \n",
    "            \n",
    "            #Calculating Returns\n",
    "            \n",
    "            ## for 1 year\n",
    "            print(\"Returns for 1 Year \\n\")\n",
    "            totalinv = amount * 12\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year1 = (equity1 + equity21 + equity31 + hybrid1 + debt1)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year1))\n",
    "            \n",
    "            totalgain = Year1 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 3 years\n",
    "            print('\\nReturns for 3 Years\\n')\n",
    "            totalinv = amount * 36\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year3 = equity3 + equity23 + equity33 + hybrid3 + debt3\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year3))\n",
    "            \n",
    "            totalgain = Year3 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))\n",
    "            \n",
    "            ## for 5 years\n",
    "            print('\\nReturns for 5 Years\\n')\n",
    "            totalinv = amount * 60\n",
    "            print('Total Amount Invested = {value:.2f}'.format(value=totalinv))\n",
    "            \n",
    "            Year5 = float(equity5) + float(equity25) + float(equity35) + float(hybrid5) + float(debt5)\n",
    "            print('Total Portfolio Value = {value:.2f}'.format(value=Year5))\n",
    "            \n",
    "            totalgain = Year5 - totalinv\n",
    "            print('Net Profit = {value:.2f}'.format(value=totalgain))\n",
    "            \n",
    "            gainper = totalgain/totalinv*100\n",
    "            print('Percentage Gained = {value:.2f}'.format(value=gainper))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f1da7c5c",
   "metadata": {},
   "source": [
    "# Dashboard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6fc47313",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please Enter your age: erhaeteath\n",
      "Please Enter appropriate Age.\n",
      "\n",
      "Please Enter your age: 1000\n",
      "Please Enter Appropriate Age.\n",
      "\n",
      "Please Enter your age: 20\n",
      "\n",
      "Please Enter Amount you wish to Invest: 5000\n",
      "\n",
      "Allocated Amount: \n",
      "Equity: 4000.00 \n",
      "Hybrid: 1000.00\n",
      "\n",
      "Please Choose an Equity Fund: \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>137</th>\n",
       "      <td>Mahindra</td>\n",
       "      <td>Mahindra Manulife Multi Cap Badhat Yojana Dire...</td>\n",
       "      <td>OTHERS/FINANCIAL/CAPITAL/TECHNOLOGY/SERVICES</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>1.11</td>\n",
       "      <td>32.13</td>\n",
       "      <td>59.92</td>\n",
       "      <td>0.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>TAURUS</td>\n",
       "      <td>Taurus Discovery (Midcap) fund direct growth</td>\n",
       "      <td>Financial/Others/Chemicals/Healthcare/Services...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>10.90</td>\n",
       "      <td>18.51</td>\n",
       "      <td>11.07</td>\n",
       "      <td>2.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>ICICI</td>\n",
       "      <td>ICICI Prudential Value Discovery Direct Growth</td>\n",
       "      <td>Financial/Energy/Healthcare/Others/Technology/...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>4.0</td>\n",
       "      <td>16.50</td>\n",
       "      <td>29.70</td>\n",
       "      <td>15.40</td>\n",
       "      <td>1.22</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     AMC_Name                                          Fund_Name  \\\n",
       "137  Mahindra  Mahindra Manulife Multi Cap Badhat Yojana Dire...   \n",
       "21     TAURUS       Taurus Discovery (Midcap) fund direct growth   \n",
       "38      ICICI     ICICI Prudential Value Discovery Direct Growth   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "137       OTHERS/FINANCIAL/CAPITAL/TECHNOLOGY/SERVICES   Equity   \n",
       "21   Financial/Others/Chemicals/Healthcare/Services...   Equity   \n",
       "38   Financial/Energy/Healthcare/Others/Technology/...   Equity   \n",
       "\n",
       "           Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "137  Very High Risk          5.0        1.11       32.13       59.92   \n",
       "21   Very High Risk          3.0       10.90       18.51       11.07   \n",
       "38   Very High Risk          4.0       16.50       29.70       15.40   \n",
       "\n",
       "     Expence_Ratio  \n",
       "137           0.44  \n",
       "21            2.19  \n",
       "38            1.22  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Type \"y\" if you want new options \n",
      "Type \"a\" if you have a specific AMC in mind.. \n",
      "Type \"n\" to continue...y\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>133</th>\n",
       "      <td>Aditya</td>\n",
       "      <td>Birla Sun Life Focused Equity Fund Direct growth</td>\n",
       "      <td>FINANACIAL/TECHNOLOGY /OTHERS/CONSTRUCTION/CON...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>3.0</td>\n",
       "      <td>-0.63</td>\n",
       "      <td>18.80</td>\n",
       "      <td>34.43</td>\n",
       "      <td>1.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>137</th>\n",
       "      <td>Mahindra</td>\n",
       "      <td>Mahindra Manulife Multi Cap Badhat Yojana Dire...</td>\n",
       "      <td>OTHERS/FINANCIAL/CAPITAL/TECHNOLOGY/SERVICES</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>1.11</td>\n",
       "      <td>32.13</td>\n",
       "      <td>59.92</td>\n",
       "      <td>0.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>55</th>\n",
       "      <td>PGIM</td>\n",
       "      <td>PGIM India Midcap Opportunities Fund Direct Gr</td>\n",
       "      <td>Consumer Durables/Industrial Products/Banks/Fi...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>5.30</td>\n",
       "      <td>32.20</td>\n",
       "      <td>18.20</td>\n",
       "      <td>0.46</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     AMC_Name                                          Fund_Name  \\\n",
       "133    Aditya   Birla Sun Life Focused Equity Fund Direct growth   \n",
       "137  Mahindra  Mahindra Manulife Multi Cap Badhat Yojana Dire...   \n",
       "55       PGIM     PGIM India Midcap Opportunities Fund Direct Gr   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "133  FINANACIAL/TECHNOLOGY /OTHERS/CONSTRUCTION/CON...   Equity   \n",
       "137       OTHERS/FINANCIAL/CAPITAL/TECHNOLOGY/SERVICES   Equity   \n",
       "55   Consumer Durables/Industrial Products/Banks/Fi...   Equity   \n",
       "\n",
       "           Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "133  Very High Risk          3.0       -0.63       18.80       34.43   \n",
       "137  Very High Risk          5.0        1.11       32.13       59.92   \n",
       "55   Very High Risk          5.0        5.30       32.20       18.20   \n",
       "\n",
       "     Expence_Ratio  \n",
       "133           1.12  \n",
       "137           0.44  \n",
       "55            0.46  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Type \"y\" if you want new options \n",
      "Type \"a\" if you have a specific AMC in mind.. \n",
      "Type \"n\" to continue...a\n",
      "['Canara' 'Axis' 'Shriram' 'Navi' 'LIC' 'TAURUS' 'PRINCIPAL' 'IIFL' 'JM'\n",
      " 'Franklin' 'Parag' 'ICICI' 'Baroda' 'PGIM' 'Sundaram' 'Union'\n",
      " 'Indiabulls' 'Templeton' 'KOTAK' 'HSBC' 'INVESCO' 'DSP' 'Motilal'\n",
      " 'Principal' 'BOI' 'Mirae' 'IDFC' 'Quant' 'Tata' 'HDFC' 'UTI' 'Edelweiss'\n",
      " 'Aditya' 'Mahindra' 'BNP' 'IDBI' 'Nippon' 'SBI' 'Bank' 'L&T']\n",
      "Please Enter your Choice: SBI\n",
      "Amc of Choice:  SBI\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>150</th>\n",
       "      <td>SBI</td>\n",
       "      <td>SBI Contra Direct Plan Growth</td>\n",
       "      <td>Financial /Energy /Others /Construction /Metal...</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>19.4</td>\n",
       "      <td>36.2</td>\n",
       "      <td>15.7</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>151</th>\n",
       "      <td>SBI</td>\n",
       "      <td>SBI Banking &amp; Financial Services Fund Direct</td>\n",
       "      <td>Financial /Insurance</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>12.4</td>\n",
       "      <td>12.6</td>\n",
       "      <td>12.7</td>\n",
       "      <td>0.79</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    AMC_Name                                     Fund_Name  \\\n",
       "150      SBI                 SBI Contra Direct Plan Growth   \n",
       "151      SBI  SBI Banking & Financial Services Fund Direct   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "150  Financial /Energy /Others /Construction /Metal...   Equity   \n",
       "151                               Financial /Insurance   Equity   \n",
       "\n",
       "           Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "150  Very High Risk          5.0        19.4        36.2        15.7   \n",
       "151  Very High Risk          5.0        12.4        12.6        12.7   \n",
       "\n",
       "     Expence_Ratio  \n",
       "150           1.00  \n",
       "151           0.79  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Please Choose a Fund from above list and Enter the Code Number Written Before AMCName\n",
      "Please Enter Your Choice: 151\n",
      "\n",
      " AMC_Name                                                  SBI\n",
      "Fund_Name        SBI Banking & Financial Services Fund Direct\n",
      "Holdings                                 Financial /Insurance\n",
      "Category                                               Equity\n",
      "Risktype                                       Very High Risk\n",
      "Fund_Rating                                               5.0\n",
      "Return_1Yr                                               12.4\n",
      "Return_3Yr                                               12.6\n",
      "Return_5Yr                                               12.7\n",
      "Expence_Ratio                                            0.79\n",
      "Name: 151, dtype: object\n",
      "\n",
      "Please Choose a Hybrid Fund\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>Baroda</td>\n",
       "      <td>Baroda BNP Paribas Aggressive Hybrid Fund Dire...</td>\n",
       "      <td>Financial/Others/Technology/Energy/Constructio...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>6.20</td>\n",
       "      <td>14.80</td>\n",
       "      <td>13.10</td>\n",
       "      <td>0.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>72</th>\n",
       "      <td>KOTAK</td>\n",
       "      <td>Kotak Debt Hybrid Fund Direct Growth</td>\n",
       "      <td>Government/Securities/Debentures/Financials/Co...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Moderate to High</td>\n",
       "      <td>4.0</td>\n",
       "      <td>8.87</td>\n",
       "      <td>11.84</td>\n",
       "      <td>10.21</td>\n",
       "      <td>0.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>Quant</td>\n",
       "      <td>Quant Absolute Fund Direct Growth</td>\n",
       "      <td>Financial/Consumer Staples/Energy/others/Const...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>31.20</td>\n",
       "      <td>19.16</td>\n",
       "      <td>0.56</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    AMC_Name                                          Fund_Name  \\\n",
       "49    Baroda  Baroda BNP Paribas Aggressive Hybrid Fund Dire...   \n",
       "72     KOTAK               Kotak Debt Hybrid Fund Direct Growth   \n",
       "113    Quant                  Quant Absolute Fund Direct Growth   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "49   Financial/Others/Technology/Energy/Constructio...   Hybrid   \n",
       "72   Government/Securities/Debentures/Financials/Co...   Hybrid   \n",
       "113  Financial/Consumer Staples/Energy/others/Const...   Hybrid   \n",
       "\n",
       "             Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "49     Very High Risk          5.0        6.20       14.80       13.10   \n",
       "72   Moderate to High          4.0        8.87       11.84       10.21   \n",
       "113    Very High Risk          5.0       17.00       31.20       19.16   \n",
       "\n",
       "     Expence_Ratio  \n",
       "49            0.61  \n",
       "72            0.44  \n",
       "113           0.56  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Type \"y\" if you want new options \n",
      "Type \"a\" if you have a specific AMC in mind.. \n",
      "Type \"n\" to continue...N\n",
      "\n",
      "Please Choose a Fund from above list and Enter the Code Number Written Before AMCName\n",
      "Please Enter Your Choice: 113\n",
      "\n",
      " AMC_Name                                                     Quant\n",
      "Fund_Name                        Quant Absolute Fund Direct Growth\n",
      "Holdings         Financial/Consumer Staples/Energy/others/Const...\n",
      "Category                                                    Hybrid\n",
      "Risktype                                            Very High Risk\n",
      "Fund_Rating                                                    5.0\n",
      "Return_1Yr                                                    17.0\n",
      "Return_3Yr                                                    31.2\n",
      "Return_5Yr                                                   19.16\n",
      "Expence_Ratio                                                 0.56\n",
      "Name: 113, dtype: object\n",
      "\n",
      "Following are the Funds you have chosen: \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>AMC_Name</th>\n",
       "      <th>Fund_Name</th>\n",
       "      <th>Holdings</th>\n",
       "      <th>Category</th>\n",
       "      <th>Risktype</th>\n",
       "      <th>Fund_Rating</th>\n",
       "      <th>Return_1Yr</th>\n",
       "      <th>Return_3Yr</th>\n",
       "      <th>Return_5Yr</th>\n",
       "      <th>Expence_Ratio</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>151</th>\n",
       "      <td>SBI</td>\n",
       "      <td>SBI Banking &amp; Financial Services Fund Direct</td>\n",
       "      <td>Financial /Insurance</td>\n",
       "      <td>Equity</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>12.4</td>\n",
       "      <td>12.6</td>\n",
       "      <td>12.70</td>\n",
       "      <td>0.79</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>113</th>\n",
       "      <td>Quant</td>\n",
       "      <td>Quant Absolute Fund Direct Growth</td>\n",
       "      <td>Financial/Consumer Staples/Energy/others/Const...</td>\n",
       "      <td>Hybrid</td>\n",
       "      <td>Very High Risk</td>\n",
       "      <td>5.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>31.2</td>\n",
       "      <td>19.16</td>\n",
       "      <td>0.56</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    AMC_Name                                     Fund_Name  \\\n",
       "151      SBI  SBI Banking & Financial Services Fund Direct   \n",
       "113    Quant             Quant Absolute Fund Direct Growth   \n",
       "\n",
       "                                              Holdings Category  \\\n",
       "151                               Financial /Insurance   Equity   \n",
       "113  Financial/Consumer Staples/Energy/others/Const...   Hybrid   \n",
       "\n",
       "           Risktype  Fund_Rating  Return_1Yr  Return_3Yr  Return_5Yr  \\\n",
       "151  Very High Risk          5.0        12.4        12.6       12.70   \n",
       "113  Very High Risk          5.0        17.0        31.2       19.16   \n",
       "\n",
       "     Expence_Ratio  \n",
       "151           0.79  \n",
       "113           0.56  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Returns for 1 Year \n",
      "\n",
      "Total Amount Invested = 60000.00\n",
      "Total Portfolio Value = 64513.85\n",
      "Net Profit = 4513.85\n",
      "Percentage Gained = 7.52\n",
      "\n",
      "Returns for 3 Years\n",
      "\n",
      "Total Amount Invested = 180000.00\n",
      "Total Portfolio Value = 235686.49\n",
      "Net Profit = 55686.49\n",
      "Percentage Gained = 30.94\n",
      "\n",
      "Returns for 5 Years\n",
      "\n",
      "Total Amount Invested = 300000.00\n",
      "Total Portfolio Value = 437370.26\n",
      "Net Profit = 137370.26\n",
      "Percentage Gained = 45.79\n"
     ]
    }
   ],
   "source": [
    "while(True):\n",
    "    age = input('Please Enter your age: ')\n",
    "    if age.isnumeric():\n",
    "        age = int(age)\n",
    "        if age > 100:\n",
    "            print('Please Enter Appropriate Age.\\n')\n",
    "        elif age <= 18:\n",
    "            per1 = 1\n",
    "            break\n",
    "        else:\n",
    "            per = 100-age\n",
    "            per1 = per/100\n",
    "            #print('\\nper: {value:.2f}'.format(value = int(per)))\n",
    "            break\n",
    "    else:\n",
    "        print('Please Enter appropriate Age.\\n')\n",
    "\n",
    "while(True):\n",
    "    while(True):\n",
    "        amount = input('\\nPlease Enter Amount you wish to Invest: ')\n",
    "        if amount.isnumeric():\n",
    "            amount = int(amount)\n",
    "            break\n",
    "        else:\n",
    "            print('\\nPlease Enter Appropriate Amount.')\n",
    "    \n",
    "    if amount < 1000:\n",
    "        print('\\nMinimum Amount should be atleast Rs.1000')\n",
    "    \n",
    "    elif amount <= 5000:\n",
    "        equity =  amount * per1 \n",
    "        hybrid = amount - equity\n",
    "        if hybrid == 0.00:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f}'.format(value = equity))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose an Equity Fund: ')\n",
    "            rowno.append(options(df, 'Equity'))\n",
    "            \n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "        else:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f}'.format(value = equity, value2 = hybrid))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose an Equity Fund: ')\n",
    "            rowno.append(options(df, 'Equity'))\n",
    "            \n",
    "            print('\\nPlease Choose a Hybrid Fund')\n",
    "            rowno.append(options(df, 'Hybrid'))\n",
    "            \n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    "            \n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "\n",
    "    elif amount > 5000 and amount <= 10000:\n",
    "        equity = amount * per1\n",
    "        var = amount - equity\n",
    "        hybrid = var / 2\n",
    "        debt = var / 2\n",
    "\n",
    "        if hybrid == 0.00 and debt == 0.00:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f} \\nDebt: {value3:.2f}'.format(value = equity, value2 = hybrid, value3 = debt))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose Your First Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 5))\n",
    "\n",
    "            print('\\nPlease Choose Your Second Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 4))\n",
    "            \n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    "\n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "        else:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f} \\nDebt: {value3:.2f}'.format(value = equity, value2 = hybrid, value3 = debt))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose Your First Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 5))\n",
    "\n",
    "            print('\\nPlease Choose Your Second Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 4))\n",
    "\n",
    "            print('\\nPlease Choose a Hybrid Fund')\n",
    "            rowno.append(options(df, 'Hybrid'))\n",
    "\n",
    "            print('\\nPlease Choose a Debt Fund')\n",
    "            rowno.append(options(df, 'Debt'))\n",
    "\n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    "\n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "        \n",
    "    elif amount > 10000:\n",
    "        equity = amount * per1\n",
    "        var = amount - equity\n",
    "        hybrid = var / 2\n",
    "        debt = var / 2\n",
    "        \n",
    "        print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f} \\nDebt: {value3:.2f}'.format(value = equity, value2 = hybrid, value3 = debt))\n",
    "        if hybrid == 0.00 and debt == 0.00:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f} \\nDebt: {value3:.2f}'.format(value = equity, value2 = hybrid, value3 = debt))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose Your First Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 5))\n",
    "\n",
    "            print('\\nPlease Choose Your Second Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 4))\n",
    "            \n",
    "            print('\\nPlease Choose Your Third Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 3))\n",
    "\n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    "\n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "        else:\n",
    "            print('\\nAllocated Amount: \\nEquity: {value:.2f} \\nHybrid: {value2:.2f} \\nDebt: {value3:.2f}'.format(value = equity, value2 = hybrid, value3 = debt))\n",
    "            rowno = []\n",
    "            print('\\nPlease Choose Your First Equity Fund: ') \n",
    "            rowno.append(optionswithrating(df, 'Equity', 5))\n",
    "\n",
    "            print('\\nPlease Choose Your Second Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 4))\n",
    "            \n",
    "            print('\\nPlease Choose Your Third Equity Fund: ')\n",
    "            rowno.append(optionswithrating(df, 'Equity', 3))\n",
    "\n",
    "            print('\\nPlease Choose a Hybrid Fund')\n",
    "            rowno.append(options(df, 'Hybrid'))\n",
    "\n",
    "            print('\\nPlease Choose a Debt Fund')\n",
    "            rowno.append(options(df, 'Debt'))\n",
    "\n",
    "            xyz = df.loc[rowno]\n",
    "            xyz.to_csv('Mutual_Funds.csv')\n",
    " \n",
    "            calculate(df, amount, age, rowno)\n",
    "            break\n",
    "\n",
    "    else:\n",
    "        print('Invalid Input')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62cd7904",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1f36cf31",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
